### ISSUE TITLE
Clean up/prettify reports

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#154]
Last main target before OHBM.

* [x] Missing contrast matrices in L1 reports (#155)
* [x] Bad value range for L1 glass brains (#155)
* [x] Bad value range for LN glass brains (#155)
* [ ] Single-page reports? (#161)
* [ ] ...

@adelavega Feel free to add any issues you see.

**Comment by oesteban** [comment]
Any interest in using the generic reporting of niworkflows? I could take on that.
